USE sonic_stream;

insert into listener (id, username, password, date_of_birth, location) values (1, 'lloader0', 'rA3/vP~ZJ@7~', '2/9/2024', 'Maciejowice');
insert into listener (id, username, password, date_of_birth, location) values (2, 'lhearle1', 'mM9@*my4', '7/22/2024', 'Shangdu');
insert into listener (id, username, password, date_of_birth, location) values (3, 'dpoll2', 'fD3!~oElml', '4/27/2024', 'Leudelange');
insert into listener (id, username, password, date_of_birth, location) values (4, 'gpollack3', 'sL3|992a6aIV*gBT', '9/9/2023', 'Molochnoye');
insert into listener (id, username, password, date_of_birth, location) values (5, 'moferris4', 'pT8''5.IDuC#v', '6/17/2024', 'Portobelo');
insert into listener (id, username, password, date_of_birth, location) values (6, 'mhuntington5', 'vR6_6WlHgB4r', '5/2/2024', 'San Isidro de Lules');
insert into listener (id, username, password, date_of_birth, location) values (7, 'lgalvan6', 'bY3_M?W|xOCE=', '8/21/2023', 'Kovernino');
insert into listener (id, username, password, date_of_birth, location) values (8, 'mdawidman7', 'vL3.Dt/N69N$,k', '5/27/2024', 'Bayonne');
insert into listener (id, username, password, date_of_birth, location) values (9, 'mrudwell8', 'gD3%t)J2R3', '6/7/2024', 'Sukacai');
insert into listener (id, username, password, date_of_birth, location) values (10, 'dmarsh9', 'rP2`T)>%m', '5/2/2024', 'Garibaldi');
insert into listener (id, username, password, date_of_birth, location) values (11, 'ecomussoa', 'cO8_@Sx_*', '6/1/2024', 'Leleque');
insert into listener (id, username, password, date_of_birth, location) values (12, 'lrachuigb', 'qX1\3#(Qt+)X+&BL', '4/14/2024', 'Kota Kinabalu');
insert into listener (id, username, password, date_of_birth, location) values (13, 'hgirardettic', 'qS1=4KrkP@p', '10/18/2023', 'Campinas');
insert into listener (id, username, password, date_of_birth, location) values (14, 'dmorlandd', 'rN6`K+wU)aZ2y', '1/29/2024', 'Choma');
insert into listener (id, username, password, date_of_birth, location) values (15, 'amullinere', 'mC6!CRBgO)/`', '11/14/2023', 'Ribnica na Pohorju');
insert into listener (id, username, password, date_of_birth, location) values (16, 'cboycef', 'wW6%CV!?d`{CFq', '9/10/2023', 'Mabunga');
insert into listener (id, username, password, date_of_birth, location) values (17, 'aelcoateg', 'tE3>H"/EaXY', '10/2/2023', 'Utrecht (stad)');
insert into listener (id, username, password, date_of_birth, location) values (18, 'vwarnerh', 'uO1#34I6', '7/4/2024', 'Zhoujiadian');
insert into listener (id, username, password, date_of_birth, location) values (19, 'rhueyi', 'eN9|3c<}*a{dKgX', '10/14/2023', 'Estevan');
insert into listener (id, username, password, date_of_birth, location) values (20, 'bgiamettij', 'rJ6{`oHYUMt3EIt', '7/22/2024', 'Nanhe');
insert into listener (id, username, password, date_of_birth, location) values (21, 'ibrinicombek', 'eA3?>V/Yx<l5', '10/7/2023', 'Tungawan');
insert into listener (id, username, password, date_of_birth, location) values (22, 'jgiacopazzil', 'gY7#76pR&', '9/11/2023', 'Merke');
insert into listener (id, username, password, date_of_birth, location) values (23, 'fleucharsm', 'aX9/!`g4AN%!"ow{', '6/8/2024', 'Talalora');
insert into listener (id, username, password, date_of_birth, location) values (24, 'astrettonn', 'jO1}mzQ4`.Bsk$r~', '3/21/2024', 'Chitose');
insert into listener (id, username, password, date_of_birth, location) values (25, 'cnibleyo', 'bR9&/tv!T!.)', '10/11/2023', 'Heping');
insert into listener (id, username, password, date_of_birth, location) values (26, 'rmacknockiterp', 'dV5,&jD"\}1', '3/19/2024', 'Bojongaren');
insert into listener (id, username, password, date_of_birth, location) values (27, 'jgoldenofirelandq', 'fX9(N>?b{Q7e\!@', '5/7/2024', 'Zapala');
insert into listener (id, username, password, date_of_birth, location) values (28, 'lducarelr', 'wV7)@Ud3Cg', '2/28/2024', 'Leticia');
insert into listener (id, username, password, date_of_birth, location) values (29, 'mgoldups', 'mR4~ZJuK', '7/21/2024', 'Sincé');
insert into listener (id, username, password, date_of_birth, location) values (30, 'wgounelt', 'iW1&r2&.M{kFKL', '12/19/2023', 'Bielice');
insert into listener (id, username, password, date_of_birth, location) values (31, 'ewadgeu', 'dK7!9N=\U#', '4/25/2024', 'Versailles');
insert into listener (id, username, password, date_of_birth, location) values (32, 'ieakinv', 'zM0|SNxvb', '8/7/2024', 'Shīrvān');
insert into listener (id, username, password, date_of_birth, location) values (33, 'arutterw', 'wH4''jJmuSR/\fH}', '1/12/2024', 'Mungkin');
insert into listener (id, username, password, date_of_birth, location) values (34, 'rtomasellox', 'hZ8)\h!|x|', '8/30/2023', 'Belsk Duży');
insert into listener (id, username, password, date_of_birth, location) values (35, 'gburkmany', 'eW3+UCzx', '9/17/2023', 'Uritsk');
insert into listener (id, username, password, date_of_birth, location) values (36, 'tjostz', 'rR1.J}yA6p{', '12/30/2023', 'Décines-Charpieu');
insert into listener (id, username, password, date_of_birth, location) values (37, 'dhebditch10', 'fA4|eF#C', '12/11/2023', 'Maceió');
insert into listener (id, username, password, date_of_birth, location) values (38, 'mzumfelde11', 'uA0&QifD&hM', '12/6/2023', 'Cigaluh');
insert into listener (id, username, password, date_of_birth, location) values (39, 'fpattingson12', 'tR0"=s~L|j=', '2/1/2024', 'Prilep');
insert into listener (id, username, password, date_of_birth, location) values (40, 'jbayly13', 'xV9$x?}4Gbj\9aII', '9/25/2023', 'Paris 08');
