USE sonic_stream;

insert into concert (id, venue, event_date) values (1, 'Dodger Stadium', '3/25/2024');
insert into concert (id, venue, event_date) values (2, 'Lambeau Field', '5/23/2024');
insert into concert (id, venue, event_date) values (3, 'Madison Square Garden', '9/27/2023');
insert into concert (id, venue, event_date) values (4, 'Madison Square Garden', '1/5/2024');
insert into concert (id, venue, event_date) values (5, 'Busch Stadium', '12/25/2023');
insert into concert (id, venue, event_date) values (6, 'Dodger Stadium', '12/29/2023');
insert into concert (id, venue, event_date) values (7, 'Soldier Field', '4/8/2024');
insert into concert (id, venue, event_date) values (8, 'Hard Rock Stadium', '1/18/2024');
insert into concert (id, venue, event_date) values (9, 'Oracle Park', '5/17/2024');
insert into concert (id, venue, event_date) values (10, 'Levi''s Stadium', '8/4/2024');
insert into concert (id, venue, event_date) values (11, 'AT&T Park', '1/14/2024');
insert into concert (id, venue, event_date) values (12, 'Arrowhead Stadium', '7/18/2024');
insert into concert (id, venue, event_date) values (13, 'Fenway Park', '4/19/2024');
insert into concert (id, venue, event_date) values (14, 'Hard Rock Stadium', '7/22/2024');
insert into concert (id, venue, event_date) values (15, 'Rose Bowl', '11/5/2023');
insert into concert (id, venue, event_date) values (16, 'Chase Field', '12/25/2023');
insert into concert (id, venue, event_date) values (17, 'Yankee Stadium', '2/8/2024');
insert into concert (id, venue, event_date) values (18, 'Soldier Field', '12/28/2023');
insert into concert (id, venue, event_date) values (19, 'Chase Field', '10/13/2023');
insert into concert (id, venue, event_date) values (20, 'Dodger Stadium', '8/19/2023');
insert into concert (id, venue, event_date) values (21, 'Dodger Stadium', '11/27/2023');
insert into concert (id, venue, event_date) values (22, 'Lambeau Field', '8/12/2023');
insert into concert (id, venue, event_date) values (23, 'Rose Bowl', '7/10/2024');
insert into concert (id, venue, event_date) values (24, 'Wells Fargo Center', '8/10/2024');
insert into concert (id, venue, event_date) values (25, 'Oracle Park', '6/24/2024');
insert into concert (id, venue, event_date) values (26, 'Wells Fargo Center', '1/24/2024');
insert into concert (id, venue, event_date) values (27, 'Chase Field', '10/5/2023');
insert into concert (id, venue, event_date) values (28, 'Dodger Stadium', '10/11/2023');
insert into concert (id, venue, event_date) values (29, 'Rose Bowl', '8/24/2023');
insert into concert (id, venue, event_date) values (30, 'Chase Field', '9/13/2023');
insert into concert (id, venue, event_date) values (31, 'Chase Field', '1/11/2024');
insert into concert (id, venue, event_date) values (32, 'Mercedes-Benz Stadium', '11/6/2023');
insert into concert (id, venue, event_date) values (33, 'Wells Fargo Center', '7/28/2024');
insert into concert (id, venue, event_date) values (34, 'Soldier Field', '12/2/2023');
insert into concert (id, venue, event_date) values (35, 'Mercedes-Benz Stadium', '6/23/2024');
insert into concert (id, venue, event_date) values (36, 'Bank of America Stadium', '5/30/2024');
insert into concert (id, venue, event_date) values (37, 'Fenway Park', '10/29/2023');
insert into concert (id, venue, event_date) values (38, 'Lambeau Field', '1/11/2024');
insert into concert (id, venue, event_date) values (39, 'Lambeau Field', '1/5/2024');
insert into concert (id, venue, event_date) values (40, 'Soldier Field', '3/3/2024');