USE sonic_stream;

insert into artist (id, name, bio) values (1, 'Taylor Swift', 'Creative director with a passion for design');
insert into artist (id, name, bio) values (2, 'Maya Thompson', 'Tech enthusiast and software developer');
insert into artist (id, name, bio) values (3, 'Beyoncé', 'Travel blogger exploring new cultures');
insert into artist (id, name, bio) values (4, 'Ed Sheeran', 'Data scientist specializing in machine learning');
insert into artist (id, name, bio) values (5, 'Ariana Grande', 'Fitness trainer dedicated to health and wellness');
insert into artist (id, name, bio) values (6, 'The Weeknd', 'Marketing strategist with a focus on digital trends');
insert into artist (id, name, bio) values (7, 'Post Malone', 'Professional chef crafting innovative recipes');
insert into artist (id, name, bio) values (8, 'Rihanna', 'Entrepreneur building sustainable startups');
insert into artist (id, name, bio) values (9, 'Billie Eilish', 'Freelance writer with a love for storytelling');
insert into artist (id, name, bio) values (10, 'Justin Bieber', 'Financial analyst with a knack for forecasting');
insert into artist (id, name, bio) values (11, 'Katy Perry', 'Graphic designer transforming ideas into visuals');
insert into artist (id, name, bio) values (12, 'Lady Gaga', 'Social media manager connecting brands with audiences');
insert into artist (id, name, bio) values (13, 'Dua Lipa', 'Public relations expert fostering positive media relationships');
insert into artist (id, name, bio) values (14, 'Kanye West', 'UX/UI designer improving user experiences');
insert into artist (id, name, bio) values (15, 'Shawn Mendes', 'Event planner organizing unforgettable experiences');
insert into artist (id, name, bio) values (16, 'Bruno Mars', 'Software engineer with expertise in cybersecurity');
insert into artist (id, name, bio) values (17, 'Cardi B', 'Music producer creating dynamic soundscapes');
insert into artist (id, name, bio) values (18, 'Lizzo', 'Architect designing modern and functional spaces');
insert into artist (id, name, bio) values (19, 'Travis Scott', 'Research scientist advancing medical discoveries');
insert into artist (id, name, bio) values (20, 'Selena Gomez', 'Fashion designer setting trends in the industry');
insert into artist (id, name, bio) values (21, 'Adele', 'Non-profit director working towards social impact');
insert into artist (id, name, bio) values (22, 'Sia', 'Product manager driving innovation and growth');
insert into artist (id, name, bio) values (23, 'Sam Smith', 'Health coach empowering clients to achieve wellness goals');
insert into artist (id, name, bio) values (24, 'Halsey', 'Data analyst uncovering insights from complex datasets');
insert into artist (id, name, bio) values (25, 'Khalid', 'Startup founder passionate about disruptive technologies');
insert into artist (id, name, bio) values (26, 'J Balvin', 'Legal consultant providing expert advice in corporate law');
insert into artist (id, name, bio) values (27, 'Bad Bunny', 'Motivational speaker inspiring audiences to achieve their potential');
insert into artist (id, name, bio) values (28, 'Janelle Monáe', 'E-commerce specialist optimizing online shopping experiences');
insert into artist (id, name, bio) values (29, 'Maroon 5', 'Web developer building responsive and user-friendly websites');
insert into artist (id, name, bio) values (30, 'Imagine Dragons', 'Brand strategist enhancing company image and market presence');
insert into artist (id, name, bio) values (31, 'Coldplay', 'Educational consultant supporting academic success');
insert into artist (id, name, bio) values (32, 'Migos', 'Art curator managing and promoting gallery exhibitions');
insert into artist (id, name, bio) values (33, 'Lil Nas X', 'Operations manager streamlining business processes');
insert into artist (id, name, bio) values (34, 'Doja Cat', 'Technical writer creating clear and concise documentation');
insert into artist (id, name, bio) values (35, 'Megan Thee Stallion', 'Customer success manager ensuring client satisfaction');
insert into artist (id, name, bio) values (36, 'Cardi B', 'Social entrepreneur addressing societal challenges');
insert into artist (id, name, bio) values (37, 'Camila Cabello', 'Musician performing and recording original compositions');
insert into artist (id, name, bio) values (38, 'Zayn Malik', 'Digital marketer executing impactful online campaigns');
insert into artist (id, name, bio) values (39, 'Twenty One Pilots', 'Research analyst conducting in-depth industry studies');
insert into artist (id, name, bio) values (40, 'Marshmello', 'Travel consultant designing personalized travel experiences');
