USE sonic_stream;

insert into song (id, album, title, genre, duration, release_date, revenue_id) values (1, '1989', 'Blank Space', 'Pop', '0:0:32', '2023-12-9', '13');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (2, 'Thriller', 'Billie Jean', 'Pop', '0:1:58', '2024-3-19', '6');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (3, 'Lemonade', 'Formation', 'R&B', '0:3:43', '2023-12-9', '11');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (4, 'divide', 'Shape of You', 'Pop', '0:3:08', '2024-8-2', '39');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (5, 'Purpose', 'Sorry', 'Pop', '0:2:20', '2023-8-21', '40');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (6, 'Dark Side of the Moon', 'Time', 'Rock', '0:4:21', '2023-12-15', '33');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (7, 'Future Nostalgia', 'Don’t Start Now', 'Disco', '0:2:56', '2023-12-22', '14');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (8, 'In the Lonely Hour', 'Stay With Me', 'Soul', '0:3:49', '2023-12-7', '9');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (9, 'Goodbye Yellow Brick Road', 'Rocket Man', 'Rock', '0:4:38', '2024-1-22', '1');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (10, 'Born to Run', 'Born to Run', 'Rock', '0:3:57', '2023-8-24', '23');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (11, 'Views', 'One Dance', 'Dancehall', '0:0:30', '2024-5-5', '27');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (12, 'The Fame', 'Just Dance', 'Pop', '0:0:22', '2024-5-31', '21');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (13, 'Blonde', 'Nikes', 'R&B', '0:3:20', '2023-12-3', '17');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (14, 'Unplugged', 'Layla', 'Rock', '0:0:21', '2023-12-10', '28');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (15, 'Rumors', 'Dreams', 'Pop', '0:2:08', '2024-6-20', '25');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (16, 'The Chronic', 'Nuthin’ but a ‘G’ Thang', 'Rap', '0:1:58', '2024-4-2', '12');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (17, 'Born This Way', 'Bad Romance', 'Rock', '0:3:34', '2024-3-2', '30');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (18, 'Recovery', 'Not Afraid', 'Pop', '0:4:44', '2024-7-29', '38');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (19, 'American Idiot', 'American Idiot', 'Hip-Hop', '0:1:24', '2024-4-1', '10');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (20, 'Hotel California', 'Hotel California', 'Rock', '0:1:56', '2023-12-24', '5');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (21, 'Abbey Road', 'Come Together', 'Rock', '0:2:04', '2023-12-3', '26');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (22, 'Happier Than Ever', 'Happier Than Ever', 'Pop', '0:2:10', '2024-5-12', '31');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (23, 'The Joshua Tree', 'With or Without You', 'Rock', '0:0:39', '2023-8-21', '36');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (24, 'Red', 'I Knew You Were Trouble', 'Pop', '0:2:39', '2023-12-19', '4');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (25, 'A Night at the Opera', 'Bohemian Rhapsody', 'Alternative Rock', '0:4:23', '2024-2-11', '22');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (26, 'Random Access Memories', 'Get Lucky', 'Pop', '0:0:53', '2024-1-6', '3');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (27, 'Midnight Memories', 'Story of My Life', 'Rap', '0:0:06', '2024-5-10', '24');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (28, 'OK Computer', 'Creep', 'Alternative Rock', '0:2:10', '2023-11-16', '18');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (29, '25', 'Hello', 'Alternative Rock', '0:0:26', '2024-8-7', '37');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (30, 'Good Kid', 'swimming pools (Drank)', 'Pop', '0:0:13', '2024-1-2', '35');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (31, 'M.A.A.D City', 'Stressed Out', 'Rock', '0:0:46', '2024-2-18', '8');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (32, 'Blurryface', 'Feel Good Inc.', 'Punk Rock', '0:4:26', '2024-2-24', '19');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (33, 'Demon Days', 'Starman', 'Rock', '0:3:26', '2024-8-6', '2');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (34, 'The Rise and Fall of Ziggy Stardust', 'You Shook Me All Night Long', 'Rock', '0:4:40', '2023-10-16', '16');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (35, 'Back in Black', 'Let It Be', 'Pop', '0:0:26', '2023-11-3', '29');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (36, 'Let It Be', 'Centuries', 'Alternative Rock', '0:4:49', '2024-2-23', '34');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (37, 'American Beauty/American Psycho', 'Lover', 'Indie Rock', '0:4:12', '2024-5-22', '20');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (38, 'Lover', 'Summertime Sadness', 'Electronic', '0:0:52', '2024-8-4', '7');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (39, 'Born to Die', 'Fix You', 'Dance', '0:1:17', '2024-2-9', '15');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (40, 'X&Y', 'Day and Night', 'Alternative Rock', '0:1:01', '2024-1-6', '32');
