insert into song (id, album, title, genre, duration, release_date, revenue_id) values (1, '1989', 'Blank Space', 'Pop', '0:32', '12/9/2023', '13');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (2, 'Thriller', 'Billie Jean', 'Pop', '1:58', '3/19/2024', '6');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (3, 'Lemonade', 'Formation', 'R&B', '3:43', '12/9/2023', '11');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (4, 'divide', 'Shape of You', 'Pop', '3:08', '8/2/2024', '39');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (5, 'Purpose', 'Sorry', 'Pop', '2:20', '8/21/2023', '40');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (6, 'Dark Side of the Moon', 'Time', 'Rock', '4:21', '12/15/2023', '33');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (7, 'Future Nostalgia', 'Don’t Start Now', 'Disco', '2:56', '12/2/2023', '14');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (8, 'In the Lonely Hour', 'Stay With Me', 'Soul', '3:49', '12/7/2023', '9');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (9, 'Goodbye Yellow Brick Road', 'Rocket Man', 'Rock', '4:38', '1/22/2024', '1');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (10, 'Born to Run', 'Born to Run', 'Rock', '3:57', '8/24/2023', '23');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (11, 'Views', 'One Dance', 'Dancehall', '0:30', '5/5/2024', '27');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (12, 'The Fame', 'Just Dance', 'Pop', '0:22', '5/31/2024', '21');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (13, 'Blonde', 'Nikes', 'R&B', '3:20', '12/3/2023', '17');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (14, 'Unplugged', 'Layla', 'Rock', '0:21', '12/10/2023', '28');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (15, 'Rumors', 'Dreams', 'Pop', '2:08', '6/20/2024', '25');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (16, 'The Chronic', 'Nuthin’ but a ‘G’ Thang', 'Rap', '1:58', '4/2/2024', '12');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (17, 'Born This Way', 'Bad Romance', 'Rock', '3:34', '3/2/2024', '30');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (18, 'Recovery', 'Not Afraid', 'Pop', '4:44', '7/29/2024', '38');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (19, 'American Idiot', 'American Idiot', 'Hip-Hop', '1:24', '4/1/2024', '10');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (20, 'Hotel California', 'Hotel California', 'Rock', '1:56', '12/24/2023', '5');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (21, 'Abbey Road', 'Come Together', 'Rock', '2:04', '12/3/2023', '26');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (22, 'Happier Than Ever', 'Happier Than Ever', 'Pop', '2:10', '5/13/2024', '31');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (23, 'The Joshua Tree', 'With or Without You', 'Rock', '0:39', '8/21/2023', '36');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (24, 'Red', 'I Knew You Were Trouble', 'Pop', '2:39', '12/19/2023', '4');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (25, 'A Night at the Opera', 'Bohemian Rhapsody', 'Alternative Rock', '4:23', '2/11/2024', '22');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (26, 'Random Access Memories', 'Get Lucky', 'Pop', '0:53', '1/6/2024', '3');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (27, 'Midnight Memories', 'Story of My Life', 'Rap', '0:06', '5/10/2024', '24');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (28, 'OK Computer', 'Creep', 'Alternative Rock', '2:10', '11/16/2023', '18');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (29, '25', 'Hello', 'Alternative Rock', '0:26', '8/7/2024', '37');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (30, 'Good Kid', 'swimming pools (Drank)', 'Pop', '0:13', '1/2/2024', '35');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (31, 'M.A.A.D City', 'Stressed Out', 'Rock', '0:46', '2/18/2024', '8');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (32, 'Blurryface', 'Feel Good Inc.', 'Punk Rock', '4:26', '2/24/2024', '19');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (33, 'Demon Days', 'Starman', 'Rock', '3:26', '8/6/2024', '2');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (34, 'The Rise and Fall of Ziggy Stardust', 'You Shook Me All Night Long', 'Rock', '4:40', '10/16/2023', '16');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (35, 'Back in Black', 'Let It Be', 'Pop', '0:26', '11/3/2023', '29');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (36, 'Let It Be', 'Centuries', 'Alternative Rock', '4:49', '2/23/2024', '34');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (37, 'American Beauty/American Psycho', 'Lover', 'Indie Rock', '4:12', '5/22/2024', '20');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (38, 'Lover', 'Summertime Sadness', 'Electronic', '0:52', '8/4/2024', '7');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (39, 'Born to Die', 'Fix You', 'Dance', '1:17', '2/9/2024', '15');
insert into song (id, album, title, genre, duration, release_date, revenue_id) values (40, 'X&Y', 'Day and Night', 'Alternative Rock', '1:01', '1/6/2024', '32');
