insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (1, 'Greenlam', 'HP', 'Toronto', '10-13', 'completed', '8');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (2, 'Flowdesk', 'Google', 'Mumbai', '13-18', 'completed', '4');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (3, 'Zathin', 'HP', 'Madrid', '18+', 'active', '3');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (4, 'Stim', 'Netflix', 'Tokyo', '18+', 'paused', '11');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (5, 'Solarbreeze', 'Salesforce', 'Los Angeles', '13-18', 'active', '28');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (6, 'Pannier', 'Microsoft', 'Paris', '10-13', 'active', '24');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (7, 'Bitchip', 'Facebook', 'Rio de Janeiro', '18+', 'completed', '19');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (8, 'Cardify', 'Dell', 'Mumbai', '13-18', 'completed', '23');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (9, 'Keylex', 'PayPal', 'Buenos Aires', '13-18', 'completed', '18');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (10, 'Vagram', 'Tesla', 'Paris', '18+', 'completed', '14');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (11, 'Cardguard', 'Google', 'Sydney', '10-13', 'paused', '6');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (12, 'Fix San', 'Sony', 'Toronto', '13-18', 'paused', '5');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (13, 'Zaam-Dox', 'Microsoft', 'Istanbul', '13-18', 'completed', '15');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (14, 'Panara', 'Cisco', 'Toronto', '10-13', 'paused', '20');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (15, 'Sonsing', 'Google', 'Los Angeles', '0-10', 'completed', '17');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (16, 'Span', 'Uber', 'Tokyo', '13-18', 'active', '27');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (17, 'Transcof', 'Cisco', 'Sydney', '10-13', 'paused', '1');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (18, 'Viva', 'Intel', 'Buenos Aires', '13-18', 'completed', '10');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (19, 'Transfusion', 'Tesla', 'Dubai', '18+', 'active', '22');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (20, 'Alphazap', 'Uber', 'Beijing', '18+', 'paused', '25');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (21, 'Bigtax', 'Tesla', 'London', '10-13', 'completed', '21');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (22, 'Tempsoft', 'Dell', 'Dubai', '0-10', 'paused', '29');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (23, 'Bitwolf', 'Uber', 'Los Angeles', '18+', 'paused', '9');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (24, 'Hatity', 'Samsung', 'Dubai', '13-18', 'active', '7');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (25, 'Konklux', 'Facebook', 'London', '13-18', 'completed', '26');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (26, 'Mat Lam Tam', 'Cisco', 'Moscow', '0-10', 'paused', '12');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (27, 'Alpha', 'Salesforce', 'Rome', '10-13', 'paused', '30');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (28, 'Treeflex', 'IBM', 'Singapore', '18+', 'paused', '16');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (29, 'Namfix', 'Amazon', 'Rome', '0-10', 'active', '2');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (30, 'Aerified', 'Tesla', 'Madrid', '10-13', 'completed', '13');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (31, 'Zontrax', 'Google', 'Singapore', '18+', 'completed', '11');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (32, 'Toughjoyfax', 'Sony', 'London', '10-13', 'paused', '6');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (33, 'Safeguard', 'Netflix', 'Rio de Janeiro', '0-10', 'active', '30');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (34, 'Daltfresh', 'Amazon', 'Berlin', '18+', 'active', '3');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (35, 'It', 'Intel', 'London', '0-10', 'completed', '10');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (36, 'Lotstring', 'Adobe', 'London', '10-13', 'active', '13');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (37, 'Lotlux', 'Tesla', 'Berlin', '0-10', 'active', '26');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (38, 'Gembucket', 'Samsung', 'Tokyo', '13-18', 'active', '12');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (39, 'Liquify', 'IBM', 'Singapore', '13-18', 'paused', '7');
insert into advertisement (id, name, company, target_location, target_age, status, revenue_id) values (40, 'Transaction', 'Salesforce', 'Dubai', '10-13', 'completed', '18');
